
export const UNIT_LIBRARY = [
  {
    id: 'xelnaga-kerrigan',
    name: "Xel'Naga Kerrigan",
    race: 'Zerg',
    baseDamage: 100,
    attackSpeed: 0.5,
    attacks: 5,
    defensePen: 25,
  },
  {
    id: 'amon',
    name: 'Amon',
    race: 'P Bio',
    baseDamage: 270,
    attackSpeed: 0.5,
    attacks: 2,
    defensePen: 25,
  },
  {
    id: 'terra-tron',
    name: 'Terra Tron',
    race: 'T Mech',
    baseDamage: 270,
    attackSpeed: 0.5,
    attacks: 1,
    defensePen: 30,
  },
  {
    id: 'spec-ops-nova',
    name: 'Spec Ops Nova',
    race: 'T Bio',
    baseDamage: 165,
    attackSpeed: 0.63,
    attacks: 2,
    defensePen: 30,
  },
  {
    id: 'spear-of-adun',
    name: 'Spear of Adun',
    race: 'P Mech',
    baseDamage: 220,
    attackSpeed: 0.5,
    attacks: 2,
    defensePen: 30,
  },
  {
    id: 'overmind',
    name: 'Overmind',
    race: 'Zerg',
    baseDamage: 145,
    attackSpeed: 2.5,
    attacks: 3,
    defensePen: 25,
  },
  {
    id: 'sarah-kerrigan',
    name: 'Sarah Kerrigan',
    race: 'Zerg, Terran',
    baseDamage: 165,
    attackSpeed: 1,
    attacks: 2,
    defensePen: 10,
  },
];
